
#include "defines.h"
#include "Arduino.h" 



const uint8_t SUBTYPE_MASK = 0xf0;
const uint8_t SUBTYPE_OFF = 4;

const uint8_t TYPE_MASK = 0x0c;
const uint8_t TYPE_OFF = 2;

const uint8_t VERSION_MASK = 0x03;
const uint8_t VERSION_OFF = 0;


const char* TYPES_NAMES[] = {"MANAGEMENT", "CONTROL", "DATA", "EXTENSION"};


const char* SUBTYPES_NAMES[] = {"ASSOCIATION_REQUEST","ASSOCIATION_RESPONSE","REASSOCIATION_REQUEST","REASSOCIATION_RESPONSE","PROBE_REQUEST","PROBE_RESPONSE","TIMING_ADVERTISEMENT","RESERVED","BEACON","ATIM","DISASSOCIATION","AUTHENTICATION","DEAUTHENTICATION","ACTION"," ACTION_NO_ACK","RESERVED",\
"RESERVED","RESERVED","TRIGGER","TACK","BEAMFORMING_REPORT_POLL","VHT_HE_NDP_ANNOUNCEMENT","CONTROL_FRAME_EXTENSION","CONTROL_WRAPPER","BLOCK_ACK_REQUEST","BLOCK_ACK","PS_POLL","RTS","CTS","ACK","CF_END","CF_END_AND_CF_ACK",\
"DATA","RESERVED","RESERVED","RESERVED","NO_DATA"," RESERVED","RESERVED","RESERVED","QOS_DATA","QOS_DATA_AND_CF_ACK","QOS_DATA_AND_CF_POLL"," QOS_DATA_AND_CF_ACK_AND_CF_POLL","QOS_NULL","RESERVED","QOS_CF_POLL","QOS_CF_ACK_AND_CF_POLL",\
"DMG_BEACON","S1G_BEACON","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED","RESERVED"};
