
#include "Arduino.h" 

#ifndef DEFINES_h
#define DEFINES_h

enum class TYPES {MANAGEMENT, CONTROL, DATA, EXTENSION};

enum class MGMT {ASSOCIATION_REQUEST,ASSOCIATION_RESPONSE,REASSOCIATION_REQUEST,REASSOCIATION_RESPONSE,PROBE_REQUEST,PROBE_RESPONSE,TIMING_ADVERTISEMENT,RESERVED,BEACON,ATIM,DISASSOCIATION,AUTHENTICATION,DEAUTHENTICATION,ACTION, ACTION_NO_ACK,RESERVED2};

enum class CTRL {RESERVED,RESERVED1,TRIGGER,TACK,BEAMFORMING_REPORT_POLL,VHT_HE_NDP_ANNOUNCEMENT,CONTROL_FRAME_EXTENSION,CONTROL_WRAPPER,BLOCK_ACK_REQUEST,BLOCK_ACK,PS_POLL,RTS,CTS,ACK,CF_END,CF_END_AND_CF_ACK};

enum class DATA {DATA,RESERVED,RESERVED1,RESERVED2,NO_DATA, RESERVED3,RESERVED4,RESERVED5,QOS_DATA,QOS_DATA_AND_CF_ACK,QOS_DATA_AND_CF_POLL, QOS_DATA_AND_CF_ACK_AND_CF_POLL,QOS_NULL,RESERVED6,QOS_CF_POLL,QOS_CF_ACK_AND_CF_POLL};

enum class EXT  {DMG_BEACON,S1G_BEACON,RESERVED};

extern const uint8_t SUBTYPE_MASK;
extern const uint8_t SUBTYPE_OFF;

extern const uint8_t TYPE_MASK;
extern const uint8_t TYPE_OFF;

extern const uint8_t VERSION_MASK;
extern const uint8_t VERSION_OFF;


extern const char* TYPES_NAMES[];
extern const char* SUBTYPES_NAMES[];



#endif